### ISSUE TITLE
only first 3 trains are exported?

### ISSUE THREAD

**Issue by breadje** [lukos/simsig_importer#37]
[Vale of Glamorgan.xlsx](https://github.com/lukos/simsig_importer/files/8127873/Vale.of.Glamorgan.xlsx)

I'm not sure what goes wrong, but the exporter only exports the first 3 trains on the down line of the attached file. There are no error codes, but train 6F72 is not mentioned at all in the resulting WTT XML.

**Comment by lukos** [comment]
Bug in the way it determines the number of columns. Need to not just take the first row's column count, which annoyingly is not necessarily the same as the others but instead find the max columns in any row.
