### ISSUE TITLE
when there are either no up or down trains in the XML the exporter creates gibberish

### ISSUE THREAD

**Issue by breadje** [lukos/simsig_importer#38]
When testing I had only specified down trains, the exported result was a train ID for the up direction that read the whole row down (the ID was 'TYPE HEADCODE POWER IN WORKING OUT WORKING DAYS') I was amazed that simsig accepted this, but it would be nicer if the exporter gracefully declined the excel file.

**Comment by lukos** [comment]
Please can you attach a spreadsheet that recreates this.

**Comment by breadje** [comment]
[Vale.of.Glamorgan no up trains.xlsx](https://github.com/lukos/simsig_importer/files/8132638/Vale.of.Glamorgan.no.up.trains.xlsx)
sure, here you are.

**Comment by lukos** [comment]
Logic problem in SpreadsheetHelper.cs, Line 208 should be checking for workingColumn == 1 instead of 0. firstCol should also start from 3, not 2 since these are 1-based.
