### ISSUE TITLE
The half minute (H) is stripped from the times

### ISSUE THREAD

**Issue by breadje** [lukos/simsig_importer#47]
The current WTT's have half minutes in them. In simsig these can be added by adding a H after the time ('11/10H'). I added this in the excel sheet ('1110H') but it looks like the 'H' is stripped from the time.

**Comment by lukos** [comment]
Yes, these are not supported yet, I didn't know this was how it was in simsig, I will look to add them.

**Comment by lukos** [comment]
Note that H adds 1 to the allowances, which are stored in multiples of 30 seconds and it adds 30 to arrival/dep times which are stored in seconds.

**Comment by lukos** [comment]
We will simply extract the current code which directly converts the times to SimSig times into a method and do a little more logic. `if (content.EndsWith("H")) ...`
