### ISSUE TITLE
Departure times ending with 'H' shown as unknown activity codes (LibreOffice issue?)

### ISSUE THREAD

**Issue by JDeeth** [lukos/simsig_importer#68]
![image](https://user-images.githubusercontent.com/847887/210188047-e2e49630-a627-4b49-903e-bf197e46aa2a.png)
I get the above error when importing this timetable created - created with LibreOffice, I don't know if this is a factor:
[Libreoffice H error demo.xlsx](https://github.com/lukos/simsig_importer/files/10329709/Libreoffice.H.error.demo.xlsx)
If I remove the H from the times they are imported without error.

**Comment by lukos** [comment]
Why do we need to accept H in the format?

**Comment by JDeeth** [comment]
For the half-minute timings e.g.:
![image](https://user-images.githubusercontent.com/847887/210440349-5d0c6d3b-1fa8-464e-9888-78c066bd22be.png)

**Comment by lukos** [comment]
That screenshot is for timetable times, which already support H. The code you changed is related to activities.

**Comment by lukos** [comment]
I can see now. The code is attempting to get activities and if it doesn't get any AND the entry was not just NNNN then it errors like you showed. You are correct with the need to change this to also accept the H, however you have also added an optional colon between the first and second pair of numbers which I don't think is correct.

**Comment by JDeeth** [comment]
Sorry, might be misremembering, I thought times could be entered either as `2118` or as (text) `21:18` (and `2118H`, `21:18H`...)?

**Comment by lukos** [comment]
Please see the PR comment. Otherwise good to go.
